var ReferrerKiller=(function(){PUB={};function escapeDoubleQuotes(str){return str.split('"').join('\\"');}function escapeSimpleQuotes(str){return str.split("'").join("\\'");}function htmlToNode(html){var container=document.createElement('div');container.innerHTML=html;return container.firstChild;}function objectToHtmlAttributes(obj){var attributes=[],value;for(var name in obj){value=obj[name];attributes.push(name+'="'+escapeDoubleQuotes(value)+'"');}return attributes.join(' ');}function htmlString(html,iframeAttributes,headExtra){var iframeAttributes=iframeAttributes||{},defaultStyles='border:none;overflow:hidden;',id;if('style' in iframeAttributes){iframeAttributes.style=defaultStyles+iframeAttributes.style;}else{iframeAttributes.style=defaultStyles;}id='__referrer_killer_'+(new Date).getTime()+Math.floor(Math.random()*9999);return '<iframe style="border 1px solid #ff0000" scrolling="no" frameborder="no" allowtransparency="true" '+objectToHtmlAttributes(iframeAttributes)+'id="'+id+'" src="javascript:\'<!doctype html><html><head><meta charset=\\\'UTF-8\\\'><style>*{margin:0;padding:0;border:0;}</style>'+(headExtra?encodeURIComponent(escapeSimpleQuotes(headExtra)):'')+'</head><script>function resizeWindow(){var elems=document.getElementsByTagName(\\\'*\\\'),width=0,'+'height=0,first=document.body.firstChild,elem;if(first.offsetHeight&&first.offsetWidth){width=first.offsetWidth;height=first.offsetHeight;}else{for(var i in elems){elem=elems[i];if(!elem.offsetWidth){continue;}width=Math.max(elem.offsetWidth,width);height=Math.max(elem.offsetHeight,height);}}var ifr=parent.document.getElementById(\\\''+id+'\\\');ifr.height=height;ifr.width=width;}</script><body onload=\\\'resizeWindow()\\\'>\'+decodeURIComponent(\''+encodeURIComponent(html)+'\')+\'</body></html>\'"></iframe>';}function linkHtml(url,innerHTML,anchorParams,iframeAttributes,styleInnerIframe,headExtra){var html;innerHTML=innerHTML||false;if(!innerHTML){innerHTML=url;}anchorParams=anchorParams||{};if(!('target' in anchorParams)||'_self'===anchorParams.target){anchorParams.target='_top';}html='<style>'+encodeURIComponent(styleInnerIframe)+'</style><a class="link" rel="noreferrer" href="'+escapeDoubleQuotes(encodeURIComponent(url))+'" '+objectToHtmlAttributes(anchorParams)+'>'+innerHTML+'</a>';return htmlString(html,iframeAttributes,headExtra);}PUB.linkHtml=linkHtml;return PUB;})();

(function($){var $scrollTo=$.scrollTo=function(target,duration,settings){$(window).scrollTo(target,duration,settings);};$scrollTo.defaults={axis:'xy',duration:parseFloat($.fn.jquery)>=1.3?0:1};$scrollTo.window=function(scope){return $(window)._scrollable();};$.fn._scrollable=function(){return this.map(function(){var elem=this,isWin=!elem.nodeName||$.inArray(elem.nodeName.toLowerCase(),['iframe','#document','html','body'])!=-1;if(!isWin)return elem;var doc=(elem.contentWindow||elem).document||elem.ownerDocument||elem;return $.browser.safari||doc.compatMode=='BackCompat'?doc.body:doc.documentElement;});};$.fn.scrollTo=function(target,duration,settings){if(typeof duration=='object'){settings=duration;duration=0;}if(typeof settings=='function')settings={onAfter:settings};if(target=='max')target=9e9;settings=$.extend({},$scrollTo.defaults,settings);duration=duration||settings.speed||settings.duration;settings.queue=settings.queue&&settings.axis.length>1;if(settings.queue)duration/=2;settings.offset=both(settings.offset);settings.over=both(settings.over);return this._scrollable().each(function(){var elem=this,$elem=$(elem),targ=target,toff,attr={},win=$elem.is('html,body');switch(typeof targ){case 'number':case 'string':if(/^([+-]=)?\d+(\.\d+)?(px|%)?$/.test(targ)){targ=both(targ);break;}targ=$(targ,this);case 'object':if(targ.is||targ.style)toff=(targ=$(targ)).offset();}$.each(settings.axis.split(''),function(i,axis){var Pos=axis=='x'?'Left':'Top',pos=Pos.toLowerCase(),key='scroll'+Pos,old=elem[key],max=$scrollTo.max(elem,axis);if(toff){attr[key]=toff[pos]+(win?0:old-$elem.offset()[pos]);if(settings.margin){attr[key]-=parseInt(targ.css('margin'+Pos))||0;attr[key]-=parseInt(targ.css('border'+Pos+'Width'))||0;}attr[key]+=settings.offset[pos]||0;if(settings.over[pos])attr[key]+=targ[axis=='x'?'width':'height']()*settings.over[pos];}else{var val=targ[pos];attr[key]=val.slice&&val.slice(-1)=='%'?parseFloat(val)/100*max:val;}if(/^\d+$/.test(attr[key]))attr[key]=attr[key]<=0?0:Math.min(attr[key],max);if(!i&&settings.queue){if(old!=attr[key])animate(settings.onAfterFirst);delete attr[key];}});animate(settings.onAfter);function animate(callback){$elem.animate(attr,duration,settings.easing,callback&&function(){callback.call(this,target,settings);});};}).end();};$scrollTo.max=function(elem,axis){var Dim=axis=='x'?'Width':'Height',scroll='scroll'+Dim;if(!$(elem).is('html,body'))return elem[scroll]-$(elem)[Dim.toLowerCase()]();var size='client'+Dim,html=elem.ownerDocument.documentElement,body=elem.ownerDocument.body;return Math.max(html[scroll],body[scroll])-Math.min(html[size],body[size]);};function both(val){return typeof val=='object'?val:{top:val,left:val};};})(jQuery);

function lcs(a){if(document.createStyleSheet)document.createStyleSheet(a);else $("head").append('<link rel="stylesheet" type="text/css" href="'+a+'" />');}
function rcs(a){$("link").each(function(){if($(this)&&$(this).attr("href")!=null&&$(this).attr("href").indexOf(a)!=-1)$(this).remove();});}function lcss(n,a){if(n!=a){lcs("/css/modos/"+n+".css");if(a!=-1)rcss(a,-1);}}function rcss(n,a){if(n!=a){rcs("/css/modos/"+n+".css");if(a!=-1)lcss(a,-1);}}

function mueveMenu(){var aboveHeight=$('#contenido').offset().top;if($(window).scrollTop()>aboveHeight)$('#menu_scroll').addClass('menu_fixed');else $('#menu_scroll').removeClass('menu_fixed');}

$(document).ready(function(){mueveMenu();$(window).scroll(function(){mueveMenu();});document.getElementById('radio1').onclick=function(){setModoPic(1);};document.getElementById('radio2').onclick=function(){setModoPic(2);};var m="invisible";var b=jQuery('#ayuda2');var c=jQuery('#ayuda1');var a=jQuery('.entrada');var f=function(){if(a.val().length>0){b.removeClass(m);c.addClass(m);}else{b.addClass(m);c.removeClass(m);}};a.blur(f);a.each(f);a.focus(function(){b.removeClass(m);c.addClass(m);});});

$("#formCalculador").submit(function(event){if(web!=""){$("#resultado").addClass("hx100");$("#resultado").html('<div class="cargando"></div>');$.scrollTo('#resultado',800);}});

function getFlashMovie(movieName){var isIE=navigator.appName.indexOf("Microsoft")!=-1;return(isIE)?window[movieName]:document[movieName];}