<?php
define('SECCION_LEGAL','Legal warning');

define('TXT_LEGAL_FULL','Descargavideos searches videos the same way as a web browser loads and executes the web that contains the video.<br>
	Descargavideos Does NOT save any information of the results as the links, titles or pictures. They are calculated each time the user puts a URL.
	<p>
	The links generated by Descargavideos belongs to other webs not related to Descargavideos and may contain, among others, subject to copyright material.<br>
	To make use of the links shown by Descargavideos the user must know and accept the related Terms of Service to the web owner of the link. It is a responsability of the user respect at any time the related Terms of Service.
	<p>
	Neither Descargavideos or his developers are responsible for the misuse of the users of this web.');
?>